title: "Ahana Chattopadhyay"
author: "Ahana Chattopadhyay"
description: "Université de Lorraine"
permalink: /:title/
lang: "en"
excerpt_separator: "\n\n\n"
date_format: "%B %d, %Y"

# Layout

show_excerpts: true        # show article excerpts on the home page
show_frame: true           # adds a gray frame to the site
show_sidebar: false        # show a sidebar instead of the usual header
minimal: false             # use a dark header

# Menu

navigation:                # accepts {file, title, url, icon, sidebaricon}
  - title: "CV"
    children:
      - title: "EN CV"
        url: /CV_M2 NLP_PhD_corrected.pdf
      - title: "FR CV"
        url: /CV_M2 TAL_doctorat.pdf
  - {file: "publication.md", title: "Publications"}
  - {file: "blog.md", title: "Blogs"}

external:                  # shows a footer with social links - for available icons see fontawesome.com/icons
  - {title: Mail, icon: envelope, url: "mailto:oldfilesstorage1@gmail.com"}
  - {title: Github, icon: github, url: "https://github.com/AhanaChattopadhyay"}
  - {title: LinkedIn, icon: linkedin, url: "https://www.linkedin.com/in/ahana-chattopadhyay-509815226/"}

comments:
#  disqus_shortname: ""    # see https://disqus.com/
#  isso_domain: ""         # see https://posativ.org/isso/

plugins:
 - jekyll-feed
